services:
  - type: web
    name: line-mention-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False